apiVersion: v1
data:
  envconsul-config.hcl: "secret {\r\n    no_prefix = true\r\n    path = \"SECRET_PATH\"\r\n}\r\n\r\nvault
    {\r\n  address     = \"VAULT_ADDR\"\r\n  token       = \"VAULT_TOKEN\"\r\n  renew_token
    = false\r\n  unwrap_token = true\r\n\r\n  ssl {\r\n    enabled = true\r\n    verify  = false\r\n  }\r\n}"
kind: ConfigMap
metadata:
  name: envconsul-configmap
  namespace: example-project
