apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-sample
  namespace: example-project
  labels:
    app: vault-sample
spec:
  replicas: 5
  selector:
    matchLabels:
      app: vault-sample-app
  template:
    metadata:
      labels:
        app: vault-sample-app
    spec:
      serviceAccountName: example-secret-reader
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory

        - name: envconsul-modified
          emptyDir:
            medium: Memory

        - name: consul-template-modified
          emptyDir:
            medium: Memory

        - name: vaultagent-modified
          emptyDir:
            medium: Memory

        - name: channel-keys
          emptyDir:
            medium: Memory

        - name: agent-config
          configMap:
            name: vault-agent-config
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl

        - name: envconsul-config
          configMap:
            name: envconsul-config
            items:
              - key: envconsul-config.hcl
                path: envconsul-config.hcl

        - name: consul-template-config
          configMap:
            name: consul-template-config
            items:
              - key: consul-template-config.hcl
                path: consul-template-config.hcl

      initContainers:
        # Vault container
        - name: vault-agent-auth
          image: vault

          volumeMounts:
            - name: agent-config
              mountPath: /etc/vault
            - name: vaultagent-modified
              mountPath: /etc/vaultmodified
            - name: vault-token
              mountPath: /home/vault

          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-addr
                  key: url
            - name: VAULT_ROLE
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: exampleRoleKey

          command: ["/bin/sh","-c"]
          args:
           -  cp /etc/vault/vault-agent-config.hcl /etc/vaultmodified/vault-agent-config.hcl;
              sed -i 's|VAULT_ROLE|'"$VAULT_ROLE"'|g' /etc/vaultmodified/vault-agent-config.hcl;
              docker-entrypoint.sh agent -config=/etc/vaultmodified/vault-agent-config.hcl;

        - name: envconsul-config-init
          image: docker.io/hilmit82/alpine-jq
          volumeMounts:
            - name: envconsul-config
              mountPath: /etc/envconsul

            - name: vault-token
              mountPath: /home/vault

            - name: envconsul-modified
              mountPath: /etc/envconsulmodified
          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-addr
                  key: url
            - name: SECRET_PATH
              valueFrom:
                secretKeyRef:
                  name: vault-secrets
                  key: exampleSecretPath
          command: ["/bin/sh","-c"]
          args:
           #export VAULT_TOKEN=$(jq -r '.token' /home/vault/.vault-token);
          - export VAULT_TOKEN=`cat /home/vault/.vault-token`;
            cp /etc/envconsul/envconsul-config.hcl /etc/envconsulmodified/envconsul-config.hcl;
            sed -i 's|SECRET_PATH|'"$SECRET_PATH"'|g' /etc/envconsulmodified/envconsul-config.hcl;
            sed -i 's|VAULT_ADDR|'"$VAULT_ADDR"'|g' /etc/envconsulmodified/envconsul-config.hcl;
            sed -i 's|VAULT_TOKEN|'"$VAULT_TOKEN"'|g' /etc/envconsulmodified/envconsul-config.hcl;

        - name: consul-template-config-init
          image: docker.io/hilmit82/consul-template-config-modifier:1.11.0
          volumeMounts:
            - name: consul-template-config
              mountPath: /etc/consultemplate

            - name: vault-token
              mountPath: /home/vault

            - name: consul-template-modified
              mountPath: /etc/consultemplatemodified
          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-addr
                  key: url
            - name: VAULT_KEY_PATH
              valueFrom:
                secretKeyRef:
                  name: channel-key-path
                  key: data
            - name: KEY_DESTINATION_PATH
              value: "/etc/keys/"

        - name: consul-template
          image: docker.io/hilmit82/consul-template-scratch:1.1.0
          volumeMounts:
            - name: channel-keys
              mountPath: /etc/keys

            - name: consul-template-modified
              mountPath: /etc/config
      containers:
        - name: microservice-container
          image: docker.io/hilmit82/sample-microservice-with-envconsul-scratch:1.10.0
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          volumeMounts:
            - name: envconsul-modified
              mountPath: /etc/envconsul
              readOnly: true

            - name: channel-keys
              mountPath: /etc/keys
              readOnly: true