apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-sample
  namespace: example-project
  labels:
    app: test-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-sample-app
  template:
    metadata:
      labels:
        app: test-sample-app
    spec:
      serviceAccountName: example-secret-reader
      volumes:
        - name: vault-token
          emptyDir:
            medium: Memory

        - name: vaultagent-modified
          emptyDir:
            medium: Memory

        - name: agent-config
          configMap:
            name: vault-agent-configmap
            items:
              - key: vault-agent-config.hcl
                path: vault-agent-config.hcl
      containers:
        # Vault container
        - name: vault-agent-auth
          image: vault

          volumeMounts:
            - name: agent-config
              mountPath: /etc/vault
            - name: vaultagent-modified
              mountPath: /etc/vaultmodified
            - name: vault-token
              mountPath: /home/vault

          env:
            - name: VAULT_ADDR
              valueFrom:
                configMapKeyRef:
                  name: vault-addr
                  key: url
            - name: VAULT_ROLE
              value: examplerole

          command: ["/bin/sh","-c"]
          args:
           -  cp /etc/vault/vault-agent-config.hcl /etc/vaultmodified/vault-agent-config.hcl;
              sed -i 's|VAULT_ROLE|'"$VAULT_ROLE"'|g' /etc/vaultmodified/vault-agent-config.hcl;
              docker-entrypoint.sh agent -config=/etc/vaultmodified/vault-agent-config.hcl;