apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault-sample
  name: vault-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9999
    nodePort: 30080
  selector:
    app: vault-sample-app
  type: NodePort
